#!/usr/bin/env python3
from __future__ import annotations

import os
import re
from pathlib import Path
from datetime import datetime, timezone

RE_MD = re.compile(r"^quantph_(\d{4})-W(\d{2})\.md$")

def parse_week_key(filename: str) -> tuple[int, int] | None:
    m = RE_MD.match(filename)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))

def main() -> None:
    repo_user = os.environ.get("REPO_OWNER", "michi66f")
    repo_name = os.environ.get("REPO_NAME", "quant-ph-feed")
    branch_or_sha = os.environ.get("REPO_REF", "main")  # main でも SHA でも可
    keep_weeks = int(os.environ.get("KEEP_WEEKS", "8"))

    md_dir = Path("data/md")
    out_path = Path("data/index_recent.md")

    if not md_dir.exists():
        raise SystemExit(f"Missing directory: {md_dir}")

    candidates: list[tuple[tuple[int, int], Path]] = []
    for p in md_dir.glob("quantph_????-W??.md"):
        key = parse_week_key(p.name)
        if key is not None:
            candidates.append((key, p))

    # 週番号でソートして直近 N 個
    candidates.sort(key=lambda x: x[0])
    recent = candidates[-keep_weeks:] if keep_weeks > 0 else candidates

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append("# Recent quant-ph weekly sources")
    lines.append("")
    lines.append("This file is auto-generated by GitHub Actions.")
    lines.append(f"Last updated: {ts}")
    lines.append("")
    lines.append("## Included weeks")
    for (y, w), p in recent:
        lines.append(f"- {y}-W{w:02d} ({p.name})")
    lines.append("")
    lines.append("## Raw source URLs")
    for (_, _), p in recent:
        raw_url = f"https://raw.githubusercontent.com/{repo_user}/{repo_name}/{branch_or_sha}/{p.as_posix()}"
        lines.append(f"- {raw_url}")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} with {len(recent)} entries.")

if __name__ == "__main__":
    main()
